#! /usr/bin/bash

g++ -o a.out src/Main.cc src/engine/Engine.cc src/engine/main/Rasterizer.cc -g -fexpensive-optimizations -flto -O -Wunreachable-code -Wno-deprecated -Wno-unknown-pragmas -DUNICODE -L. -lm -lX11 -lGL -lpthread -lpng -lstdc++fs -std=c++17