#! /usr/bin/bash

g++ -o a.out src/math/Vector.cc src/math/Matrix.cc src/math/mesh/Mesh.cc src/dynamics/Dynamics.cc src/main/Rasterizer.cc src/main/Main.cc -g -fexpensive-optimizations -flto -Ofast -Wunreachable-code -Wno-deprecated -Wno-unknown-pragmas -DUNICODE -L. -lm -lX11 -lGL -lpthread -lpng -lstdc++fs -std=c++17