#! /usr/bin/bash

g++ -o a.out src/math/Maths.cc src/dynamics/Dynamics.cc src/main/Rasterizer.cc src/main/Main.cc -g -fexpensive-optimizations -flto -O -Wunreachable-code -Wno-deprecated -Wno-unknown-pragmas -DUNICODE -L. -lm -lX11 -lGL -lpthread -lpng -lstdc++fs -std=c++17